//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler hatalı davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationWS
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_ERRORType
    {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int eRROR_CODEField;
        
        private string eRROR_SHORT_DESField;
        
        private string eRROR_LONG_DESField;
        
        private string sTACKTRACEField;
        
        private int eRROR_ELEMENT_INDEXField;
        
        private bool eRROR_ELEMENT_INDEXFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long INTL_TXN_ID
        {
            get
            {
                return this.iNTL_TXN_IDField;
            }
            set
            {
                this.iNTL_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID
        {
            get
            {
                return this.cLIENT_TXN_IDField;
            }
            set
            {
                this.cLIENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int ERROR_CODE
        {
            get
            {
                return this.eRROR_CODEField;
            }
            set
            {
                this.eRROR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ERROR_SHORT_DES
        {
            get
            {
                return this.eRROR_SHORT_DESField;
            }
            set
            {
                this.eRROR_SHORT_DESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ERROR_LONG_DES
        {
            get
            {
                return this.eRROR_LONG_DESField;
            }
            set
            {
                this.eRROR_LONG_DESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string STACKTRACE
        {
            get
            {
                return this.sTACKTRACEField;
            }
            set
            {
                this.sTACKTRACEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int ERROR_ELEMENT_INDEX
        {
            get
            {
                return this.eRROR_ELEMENT_INDEXField;
            }
            set
            {
                this.eRROR_ELEMENT_INDEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERROR_ELEMENT_INDEXSpecified
        {
            get
            {
                return this.eRROR_ELEMENT_INDEXFieldSpecified;
            }
            set
            {
                this.eRROR_ELEMENT_INDEXFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LoginResponse
    {
        
        private string sESSION_IDField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string SESSION_ID
        {
            get
            {
                return this.sESSION_IDField;
            }
            set
            {
                this.sESSION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE
        {
            get
            {
                return this.eRROR_TYPEField;
            }
            set
            {
                this.eRROR_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GIBUSER
    {
        
        private string iDENTIFIERField;
        
        private string aLIASField;
        
        private string tITLEField;
        
        private string tYPEField;
        
        private string rEGISTER_TIMEField;
        
        private string uNITField;
        
        private string aLIAS_CREATION_TIMEField;
        
        private string aCCOUNT_TYPEField;
        
        private string dELETEDField;
        
        private string aLIAS_DELETION_TIMEField;
        
        private string dOCUMENT_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDENTIFIER
        {
            get
            {
                return this.iDENTIFIERField;
            }
            set
            {
                this.iDENTIFIERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ALIAS
        {
            get
            {
                return this.aLIASField;
            }
            set
            {
                this.aLIASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TITLE
        {
            get
            {
                return this.tITLEField;
            }
            set
            {
                this.tITLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string REGISTER_TIME
        {
            get
            {
                return this.rEGISTER_TIMEField;
            }
            set
            {
                this.rEGISTER_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=5)]
        public string UNIT
        {
            get
            {
                return this.uNITField;
            }
            set
            {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ALIAS_CREATION_TIME
        {
            get
            {
                return this.aLIAS_CREATION_TIMEField;
            }
            set
            {
                this.aLIAS_CREATION_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ACCOUNT_TYPE
        {
            get
            {
                return this.aCCOUNT_TYPEField;
            }
            set
            {
                this.aCCOUNT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string DELETED
        {
            get
            {
                return this.dELETEDField;
            }
            set
            {
                this.dELETEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ALIAS_DELETION_TIME
        {
            get
            {
                return this.aLIAS_DELETION_TIMEField;
            }
            set
            {
                this.aLIAS_DELETION_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DOCUMENT_TYPE
        {
            get
            {
                return this.dOCUMENT_TYPEField;
            }
            set
            {
                this.dOCUMENT_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class ATTRIBUTESTYPE
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private string nAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class CHANGE_INFOType
    {
        
        private System.DateTime cDATEField;
        
        private long cPOSITION_IDField;
        
        private long cUSER_IDField;
        
        private System.DateTime uDATEField;
        
        private bool uDATEFieldSpecified;
        
        private long uPOSITION_IDField;
        
        private bool uPOSITION_IDFieldSpecified;
        
        private long uUSER_IDField;
        
        private bool uUSER_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime CDATE
        {
            get
            {
                return this.cDATEField;
            }
            set
            {
                this.cDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long CPOSITION_ID
        {
            get
            {
                return this.cPOSITION_IDField;
            }
            set
            {
                this.cPOSITION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long CUSER_ID
        {
            get
            {
                return this.cUSER_IDField;
            }
            set
            {
                this.cUSER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime UDATE
        {
            get
            {
                return this.uDATEField;
            }
            set
            {
                this.uDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UDATESpecified
        {
            get
            {
                return this.uDATEFieldSpecified;
            }
            set
            {
                this.uDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long UPOSITION_ID
        {
            get
            {
                return this.uPOSITION_IDField;
            }
            set
            {
                this.uPOSITION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UPOSITION_IDSpecified
        {
            get
            {
                return this.uPOSITION_IDFieldSpecified;
            }
            set
            {
                this.uPOSITION_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long UUSER_ID
        {
            get
            {
                return this.uUSER_IDField;
            }
            set
            {
                this.uUSER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UUSER_IDSpecified
        {
            get
            {
                return this.uUSER_IDFieldSpecified;
            }
            set
            {
                this.uUSER_IDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_HEADERType
    {
        
        private string sESSION_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private long iNTL_TXN_IDField;
        
        private bool iNTL_TXN_IDFieldSpecified;
        
        private long iNTL_PARENT_TXN_IDField;
        
        private bool iNTL_PARENT_TXN_IDFieldSpecified;
        
        private System.DateTime aCTION_DATEField;
        
        private bool aCTION_DATEFieldSpecified;
        
        private CHANGE_INFOType cHANGE_INFOField;
        
        private string rEASONField;
        
        private string aPPLICATION_NAMEField;
        
        private string hOSTNAMEField;
        
        private string cHANNEL_NAMEField;
        
        private string sIMULATION_FLAGField;
        
        private string cOMPRESSEDField;
        
        private ATTRIBUTESTYPE[] aTTRIBUTESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string SESSION_ID
        {
            get
            {
                return this.sESSION_IDField;
            }
            set
            {
                this.sESSION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID
        {
            get
            {
                return this.cLIENT_TXN_IDField;
            }
            set
            {
                this.cLIENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long INTL_TXN_ID
        {
            get
            {
                return this.iNTL_TXN_IDField;
            }
            set
            {
                this.iNTL_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_TXN_IDSpecified
        {
            get
            {
                return this.iNTL_TXN_IDFieldSpecified;
            }
            set
            {
                this.iNTL_TXN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long INTL_PARENT_TXN_ID
        {
            get
            {
                return this.iNTL_PARENT_TXN_IDField;
            }
            set
            {
                this.iNTL_PARENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_PARENT_TXN_IDSpecified
        {
            get
            {
                return this.iNTL_PARENT_TXN_IDFieldSpecified;
            }
            set
            {
                this.iNTL_PARENT_TXN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime ACTION_DATE
        {
            get
            {
                return this.aCTION_DATEField;
            }
            set
            {
                this.aCTION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACTION_DATESpecified
        {
            get
            {
                return this.aCTION_DATEFieldSpecified;
            }
            set
            {
                this.aCTION_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public CHANGE_INFOType CHANGE_INFO
        {
            get
            {
                return this.cHANGE_INFOField;
            }
            set
            {
                this.cHANGE_INFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=6)]
        public string REASON
        {
            get
            {
                return this.rEASONField;
            }
            set
            {
                this.rEASONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=7)]
        public string APPLICATION_NAME
        {
            get
            {
                return this.aPPLICATION_NAMEField;
            }
            set
            {
                this.aPPLICATION_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=8)]
        public string HOSTNAME
        {
            get
            {
                return this.hOSTNAMEField;
            }
            set
            {
                this.hOSTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=9)]
        public string CHANNEL_NAME
        {
            get
            {
                return this.cHANNEL_NAMEField;
            }
            set
            {
                this.cHANNEL_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=10)]
        public string SIMULATION_FLAG
        {
            get
            {
                return this.sIMULATION_FLAGField;
            }
            set
            {
                this.sIMULATION_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=11)]
        public string COMPRESSED
        {
            get
            {
                return this.cOMPRESSEDField;
            }
            set
            {
                this.cOMPRESSEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ATTRIBUTES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public ATTRIBUTESTYPE[] ATTRIBUTES
        {
            get
            {
                return this.aTTRIBUTESField;
            }
            set
            {
                this.aTTRIBUTESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogoutRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetGibUserListRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAccountRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckUserRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUserAuthorizationRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST
    {
        
        private REQUEST_HEADERType rEQUEST_HEADERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_HEADERType REQUEST_HEADER
        {
            get
            {
                return this.rEQUEST_HEADERField;
            }
            set
            {
                this.rEQUEST_HEADERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LogoutRequest : REQUEST
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetGibUserListRequest : REQUEST
    {
        
        private string tYPEField;
        
        private string dOCUMENT_TYPEField;
        
        private System.DateTime rEGISTER_TIME_STARTField;
        
        private bool rEGISTER_TIME_STARTFieldSpecified;
        
        private ALIAS_TYPE aLIAS_TYPEField;
        
        private bool aLIAS_TYPEFieldSpecified;
        
        private System.DateTime aLIAS_MODIFY_DATEField;
        
        private bool aLIAS_MODIFY_DATEFieldSpecified;
        
        public GetGibUserListRequest()
        {
            this.tYPEField = "XML";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.ComponentModel.DefaultValueAttribute("XML")]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string DOCUMENT_TYPE
        {
            get
            {
                return this.dOCUMENT_TYPEField;
            }
            set
            {
                this.dOCUMENT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime REGISTER_TIME_START
        {
            get
            {
                return this.rEGISTER_TIME_STARTField;
            }
            set
            {
                this.rEGISTER_TIME_STARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REGISTER_TIME_STARTSpecified
        {
            get
            {
                return this.rEGISTER_TIME_STARTFieldSpecified;
            }
            set
            {
                this.rEGISTER_TIME_STARTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ALIAS_TYPE ALIAS_TYPE
        {
            get
            {
                return this.aLIAS_TYPEField;
            }
            set
            {
                this.aLIAS_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ALIAS_TYPESpecified
        {
            get
            {
                return this.aLIAS_TYPEFieldSpecified;
            }
            set
            {
                this.aLIAS_TYPEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime ALIAS_MODIFY_DATE
        {
            get
            {
                return this.aLIAS_MODIFY_DATEField;
            }
            set
            {
                this.aLIAS_MODIFY_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ALIAS_MODIFY_DATESpecified
        {
            get
            {
                return this.aLIAS_MODIFY_DATEFieldSpecified;
            }
            set
            {
                this.aLIAS_MODIFY_DATEFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum ALIAS_TYPE
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        GB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetAccountRequest : REQUEST
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LoginRequest : REQUEST
    {
        
        private string uSER_NAMEField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string USER_NAME
        {
            get
            {
                return this.uSER_NAMEField;
            }
            set
            {
                this.uSER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PASSWORD
        {
            get
            {
                return this.pASSWORDField;
            }
            set
            {
                this.pASSWORDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class CheckUserRequest : REQUEST
    {
        
        private GIBUSER uSERField;
        
        private string dOCUMENT_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GIBUSER USER
        {
            get
            {
                return this.uSERField;
            }
            set
            {
                this.uSERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string DOCUMENT_TYPE
        {
            get
            {
                return this.dOCUMENT_TYPEField;
            }
            set
            {
                this.dOCUMENT_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUserAuthorizationRequest : REQUEST
    {
        
        private PRODUCT pRODUCTField;
        
        private PRODUCT_DETAIL_FLAG pRODUCT_DETAIL_FLAGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PRODUCT PRODUCT
        {
            get
            {
                return this.pRODUCTField;
            }
            set
            {
                this.pRODUCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PRODUCT_DETAIL_FLAG PRODUCT_DETAIL_FLAG
        {
            get
            {
                return this.pRODUCT_DETAIL_FLAGField;
            }
            set
            {
                this.pRODUCT_DETAIL_FLAGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum PRODUCT
    {
        
        /// <remarks/>
        EINVOICE,
        
        /// <remarks/>
        EARCHIVE,
        
        /// <remarks/>
        EDESPATCH,
        
        /// <remarks/>
        CREDITNOTE,
        
        /// <remarks/>
        RECONCILIATION,
        
        /// <remarks/>
        CONNECTOR,
        
        /// <remarks/>
        ELEDGER,
        
        /// <remarks/>
        ELEDGERARCHIVE,
        
        /// <remarks/>
        EINVOICEARCHIVE,
        
        /// <remarks/>
        ESMM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum PRODUCT_DETAIL_FLAG
    {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", ConfigurationName="AuthenticationWS.AuthenticationServicePort")]
    public interface AuthenticationServicePort
    {
        
        // CODEGEN: Login işlemi RPC ya da belge sarmalamalı olmadığından, ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LoginRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/Login/Fault/RequestFault" +
            "Message", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        AuthenticationWS.LoginResponse1 Login(AuthenticationWS.LoginRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LoginRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LoginResponse")]
        System.Threading.Tasks.Task<AuthenticationWS.LoginResponse1> LoginAsync(AuthenticationWS.LoginRequest1 request);
        
        // CODEGEN: GetUserAuthorization işlemi RPC ya da belge sarmalamalı olmadığından, ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorizationRequ" +
            "est", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorizationResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorization/Fau" +
            "lt/RequestFaultMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        AuthenticationWS.GetUserAuthorizationResponse1 GetUserAuthorization(AuthenticationWS.GetUserAuthorizationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorizationRequ" +
            "est", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetUserAuthorizationResp" +
            "onse")]
        System.Threading.Tasks.Task<AuthenticationWS.GetUserAuthorizationResponse1> GetUserAuthorizationAsync(AuthenticationWS.GetUserAuthorizationRequest1 request);
        
        // CODEGEN: GetAccount işlemi RPC ya da belge sarmalamalı olmadığından, ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccountRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccount/Fault/Request" +
            "FaultMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        AuthenticationWS.GetAccountResponse1 GetAccount(AuthenticationWS.GetAccountRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccountRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetAccountResponse")]
        System.Threading.Tasks.Task<AuthenticationWS.GetAccountResponse1> GetAccountAsync(AuthenticationWS.GetAccountRequest1 request);
        
        // CODEGEN: Logout işlemi RPC ya da belge sarmalamalı olmadığından, ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LogoutRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/Logout/Fault/RequestFaul" +
            "tMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        AuthenticationWS.LogoutResponse1 Logout(AuthenticationWS.LogoutRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LogoutRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/LogoutResponse")]
        System.Threading.Tasks.Task<AuthenticationWS.LogoutResponse1> LogoutAsync(AuthenticationWS.LogoutRequest1 request);
        
        // CODEGEN: CheckUser işlemi RPC ya da belge sarmalamalı olmadığından, ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUserRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUser/Fault/RequestF" +
            "aultMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        AuthenticationWS.CheckUserResponse1 CheckUser(AuthenticationWS.CheckUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUserRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/CheckUserResponse")]
        System.Threading.Tasks.Task<AuthenticationWS.CheckUserResponse1> CheckUserAsync(AuthenticationWS.CheckUserRequest1 request);
        
        // CODEGEN: GetGibUserList işlemi RPC ya da belge sarmalamalı olmadığından, ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserListRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserList/Fault/Req" +
            "uestFaultMessage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        AuthenticationWS.GetGibUserListResponse1 GetGibUserList(AuthenticationWS.GetGibUserListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserListRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/AuthenticationServicePort/GetGibUserListResponse")]
        System.Threading.Tasks.Task<AuthenticationWS.GetGibUserListResponse1> GetGibUserListAsync(AuthenticationWS.GetGibUserListRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.LoginRequest LoginRequest;
        
        public LoginRequest1()
        {
        }
        
        public LoginRequest1(AuthenticationWS.LoginRequest LoginRequest)
        {
            this.LoginRequest = LoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.LoginResponse LoginResponse;
        
        public LoginResponse1()
        {
        }
        
        public LoginResponse1(AuthenticationWS.LoginResponse LoginResponse)
        {
            this.LoginResponse = LoginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUserAuthorizationResponse
    {
        
        private AUTHORIZED aUTHORIZEDField;
        
        private bool aUTHORIZEDFieldSpecified;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private PRODUCT[] pRODUCT_LISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AUTHORIZED AUTHORIZED
        {
            get
            {
                return this.aUTHORIZEDField;
            }
            set
            {
                this.aUTHORIZEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AUTHORIZEDSpecified
        {
            get
            {
                return this.aUTHORIZEDFieldSpecified;
            }
            set
            {
                this.aUTHORIZEDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE
        {
            get
            {
                return this.eRROR_TYPEField;
            }
            set
            {
                this.eRROR_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PRODUCT[] PRODUCT_LIST
        {
            get
            {
                return this.pRODUCT_LISTField;
            }
            set
            {
                this.pRODUCT_LISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum AUTHORIZED
    {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthorizationRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.GetUserAuthorizationRequest GetUserAuthorizationRequest;
        
        public GetUserAuthorizationRequest1()
        {
        }
        
        public GetUserAuthorizationRequest1(AuthenticationWS.GetUserAuthorizationRequest GetUserAuthorizationRequest)
        {
            this.GetUserAuthorizationRequest = GetUserAuthorizationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthorizationResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.GetUserAuthorizationResponse GetUserAuthorizationResponse;
        
        public GetUserAuthorizationResponse1()
        {
        }
        
        public GetUserAuthorizationResponse1(AuthenticationWS.GetUserAuthorizationResponse GetUserAuthorizationResponse)
        {
            this.GetUserAuthorizationResponse = GetUserAuthorizationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetAccountResponse
    {
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private ACCOUNT_ADDRESS aCCOUNT_ADDRESSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_ERRORType ERROR_TYPE
        {
            get
            {
                return this.eRROR_TYPEField;
            }
            set
            {
                this.eRROR_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ACCOUNT_ADDRESS ACCOUNT_ADDRESS
        {
            get
            {
                return this.aCCOUNT_ADDRESSField;
            }
            set
            {
                this.aCCOUNT_ADDRESSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class ACCOUNT_ADDRESS
    {
        
        private string cOMMERCIAL_NAMEField;
        
        private string fIRST_NAMEField;
        
        private string lAST_NAMEField;
        
        private string vKN_TCKNOField;
        
        private string eMAILField;
        
        private string wEBSITEField;
        
        private string tAX_OFFICEField;
        
        private string sICIL_NOField;
        
        private string mERSIS_NOField;
        
        private string iSLETME_MERKEZIField;
        
        private string sTREETField;
        
        private string bUILDING_NAMEField;
        
        private string bUILDING_NOField;
        
        private string hOUSE_NOField;
        
        private string sUB_CITYField;
        
        private string dISTRICTField;
        
        private string cITYField;
        
        private string rEGIONField;
        
        private string cOUNTRYField;
        
        private string pOSTAL_CODEField;
        
        private string tELNOField;
        
        private string fAXNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string COMMERCIAL_NAME
        {
            get
            {
                return this.cOMMERCIAL_NAMEField;
            }
            set
            {
                this.cOMMERCIAL_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FIRST_NAME
        {
            get
            {
                return this.fIRST_NAMEField;
            }
            set
            {
                this.fIRST_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LAST_NAME
        {
            get
            {
                return this.lAST_NAMEField;
            }
            set
            {
                this.lAST_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VKN_TCKNO
        {
            get
            {
                return this.vKN_TCKNOField;
            }
            set
            {
                this.vKN_TCKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EMAIL
        {
            get
            {
                return this.eMAILField;
            }
            set
            {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=5)]
        public string WEBSITE
        {
            get
            {
                return this.wEBSITEField;
            }
            set
            {
                this.wEBSITEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TAX_OFFICE
        {
            get
            {
                return this.tAX_OFFICEField;
            }
            set
            {
                this.tAX_OFFICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SICIL_NO
        {
            get
            {
                return this.sICIL_NOField;
            }
            set
            {
                this.sICIL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MERSIS_NO
        {
            get
            {
                return this.mERSIS_NOField;
            }
            set
            {
                this.mERSIS_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ISLETME_MERKEZI
        {
            get
            {
                return this.iSLETME_MERKEZIField;
            }
            set
            {
                this.iSLETME_MERKEZIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string STREET
        {
            get
            {
                return this.sTREETField;
            }
            set
            {
                this.sTREETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string BUILDING_NAME
        {
            get
            {
                return this.bUILDING_NAMEField;
            }
            set
            {
                this.bUILDING_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string BUILDING_NO
        {
            get
            {
                return this.bUILDING_NOField;
            }
            set
            {
                this.bUILDING_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string HOUSE_NO
        {
            get
            {
                return this.hOUSE_NOField;
            }
            set
            {
                this.hOUSE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string SUB_CITY
        {
            get
            {
                return this.sUB_CITYField;
            }
            set
            {
                this.sUB_CITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string DISTRICT
        {
            get
            {
                return this.dISTRICTField;
            }
            set
            {
                this.dISTRICTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=16)]
        public string CITY
        {
            get
            {
                return this.cITYField;
            }
            set
            {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string REGION
        {
            get
            {
                return this.rEGIONField;
            }
            set
            {
                this.rEGIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string COUNTRY
        {
            get
            {
                return this.cOUNTRYField;
            }
            set
            {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string POSTAL_CODE
        {
            get
            {
                return this.pOSTAL_CODEField;
            }
            set
            {
                this.pOSTAL_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string TELNO
        {
            get
            {
                return this.tELNOField;
            }
            set
            {
                this.tELNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string FAXNO
        {
            get
            {
                return this.fAXNOField;
            }
            set
            {
                this.fAXNOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.GetAccountRequest GetAccountRequest;
        
        public GetAccountRequest1()
        {
        }
        
        public GetAccountRequest1(AuthenticationWS.GetAccountRequest GetAccountRequest)
        {
            this.GetAccountRequest = GetAccountRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.GetAccountResponse GetAccountResponse;
        
        public GetAccountResponse1()
        {
        }
        
        public GetAccountResponse1(AuthenticationWS.GetAccountResponse GetAccountResponse)
        {
            this.GetAccountResponse = GetAccountResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class LogoutResponse
    {
        
        private REQUEST_RETURNType rEQUEST_RETURNField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_RETURNType REQUEST_RETURN
        {
            get
            {
                return this.rEQUEST_RETURNField;
            }
            set
            {
                this.rEQUEST_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE
        {
            get
            {
                return this.eRROR_TYPEField;
            }
            set
            {
                this.eRROR_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_RETURNType
    {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int rETURN_CODEField;
        
        private string[] wARNINGSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long INTL_TXN_ID
        {
            get
            {
                return this.iNTL_TXN_IDField;
            }
            set
            {
                this.iNTL_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID
        {
            get
            {
                return this.cLIENT_TXN_IDField;
            }
            set
            {
                this.cLIENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int RETURN_CODE
        {
            get
            {
                return this.rETURN_CODEField;
            }
            set
            {
                this.rETURN_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WARNINGS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string[] WARNINGS
        {
            get
            {
                return this.wARNINGSField;
            }
            set
            {
                this.wARNINGSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.LogoutRequest LogoutRequest;
        
        public LogoutRequest1()
        {
        }
        
        public LogoutRequest1(AuthenticationWS.LogoutRequest LogoutRequest)
        {
            this.LogoutRequest = LogoutRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.LogoutResponse LogoutResponse;
        
        public LogoutResponse1()
        {
        }
        
        public LogoutResponse1(AuthenticationWS.LogoutResponse LogoutResponse)
        {
            this.LogoutResponse = LogoutResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class CheckUserResponse
    {
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        private GIBUSER[] uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_ERRORType ERROR_TYPE
        {
            get
            {
                return this.eRROR_TYPEField;
            }
            set
            {
                this.eRROR_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public GIBUSER[] USER
        {
            get
            {
                return this.uSERField;
            }
            set
            {
                this.uSERField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.CheckUserRequest CheckUserRequest;
        
        public CheckUserRequest1()
        {
        }
        
        public CheckUserRequest1(AuthenticationWS.CheckUserRequest CheckUserRequest)
        {
            this.CheckUserRequest = CheckUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.CheckUserResponse CheckUserResponse;
        
        public CheckUserResponse1()
        {
        }
        
        public CheckUserResponse1(AuthenticationWS.CheckUserResponse CheckUserResponse)
        {
            this.CheckUserResponse = CheckUserResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetGibUserListResponse
    {
        
        private base64Binary cONTENTField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public base64Binary CONTENT
        {
            get
            {
                return this.cONTENTField;
            }
            set
            {
                this.cONTENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_ERRORType ERROR_TYPE
        {
            get
            {
                return this.eRROR_TYPEField;
            }
            set
            {
                this.eRROR_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
    public partial class base64Binary
    {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGibUserListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.GetGibUserListRequest GetGibUserListRequest;
        
        public GetGibUserListRequest1()
        {
        }
        
        public GetGibUserListRequest1(AuthenticationWS.GetGibUserListRequest GetGibUserListRequest)
        {
            this.GetGibUserListRequest = GetGibUserListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGibUserListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public AuthenticationWS.GetGibUserListResponse GetGibUserListResponse;
        
        public GetGibUserListResponse1()
        {
        }
        
        public GetGibUserListResponse1(AuthenticationWS.GetGibUserListResponse GetGibUserListResponse)
        {
            this.GetGibUserListResponse = GetGibUserListResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface AuthenticationServicePortChannel : AuthenticationWS.AuthenticationServicePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AuthenticationServicePortClient : System.ServiceModel.ClientBase<AuthenticationWS.AuthenticationServicePort>, AuthenticationWS.AuthenticationServicePort
    {
        
        /// <summary>
        /// Hizmet uç noktasını yapılandırmak için bu kısmi metodu uygulayın.
        /// </summary>
        /// <param name="serviceEndpoint">Yapılandırılacak uç nokta</param>
        /// <param name="clientCredentials">İstemci kimlik bilgileri</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenticationServicePortClient() : 
                base(AuthenticationServicePortClient.GetDefaultBinding(), AuthenticationServicePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AuthenticationPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServicePortClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenticationServicePortClient.GetBindingForEndpoint(endpointConfiguration), AuthenticationServicePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServicePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenticationServicePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServicePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenticationServicePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationWS.LoginResponse1 AuthenticationWS.AuthenticationServicePort.Login(AuthenticationWS.LoginRequest1 request)
        {
            return base.Channel.Login(request);
        }
        
        public AuthenticationWS.LoginResponse Login(AuthenticationWS.LoginRequest LoginRequest)
        {
            AuthenticationWS.LoginRequest1 inValue = new AuthenticationWS.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            AuthenticationWS.LoginResponse1 retVal = ((AuthenticationWS.AuthenticationServicePort)(this)).Login(inValue);
            return retVal.LoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationWS.LoginResponse1> AuthenticationWS.AuthenticationServicePort.LoginAsync(AuthenticationWS.LoginRequest1 request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationWS.LoginResponse1> LoginAsync(AuthenticationWS.LoginRequest LoginRequest)
        {
            AuthenticationWS.LoginRequest1 inValue = new AuthenticationWS.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            return ((AuthenticationWS.AuthenticationServicePort)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationWS.GetUserAuthorizationResponse1 AuthenticationWS.AuthenticationServicePort.GetUserAuthorization(AuthenticationWS.GetUserAuthorizationRequest1 request)
        {
            return base.Channel.GetUserAuthorization(request);
        }
        
        public AuthenticationWS.GetUserAuthorizationResponse GetUserAuthorization(AuthenticationWS.GetUserAuthorizationRequest GetUserAuthorizationRequest)
        {
            AuthenticationWS.GetUserAuthorizationRequest1 inValue = new AuthenticationWS.GetUserAuthorizationRequest1();
            inValue.GetUserAuthorizationRequest = GetUserAuthorizationRequest;
            AuthenticationWS.GetUserAuthorizationResponse1 retVal = ((AuthenticationWS.AuthenticationServicePort)(this)).GetUserAuthorization(inValue);
            return retVal.GetUserAuthorizationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationWS.GetUserAuthorizationResponse1> AuthenticationWS.AuthenticationServicePort.GetUserAuthorizationAsync(AuthenticationWS.GetUserAuthorizationRequest1 request)
        {
            return base.Channel.GetUserAuthorizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationWS.GetUserAuthorizationResponse1> GetUserAuthorizationAsync(AuthenticationWS.GetUserAuthorizationRequest GetUserAuthorizationRequest)
        {
            AuthenticationWS.GetUserAuthorizationRequest1 inValue = new AuthenticationWS.GetUserAuthorizationRequest1();
            inValue.GetUserAuthorizationRequest = GetUserAuthorizationRequest;
            return ((AuthenticationWS.AuthenticationServicePort)(this)).GetUserAuthorizationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationWS.GetAccountResponse1 AuthenticationWS.AuthenticationServicePort.GetAccount(AuthenticationWS.GetAccountRequest1 request)
        {
            return base.Channel.GetAccount(request);
        }
        
        public AuthenticationWS.GetAccountResponse GetAccount(AuthenticationWS.GetAccountRequest GetAccountRequest)
        {
            AuthenticationWS.GetAccountRequest1 inValue = new AuthenticationWS.GetAccountRequest1();
            inValue.GetAccountRequest = GetAccountRequest;
            AuthenticationWS.GetAccountResponse1 retVal = ((AuthenticationWS.AuthenticationServicePort)(this)).GetAccount(inValue);
            return retVal.GetAccountResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationWS.GetAccountResponse1> AuthenticationWS.AuthenticationServicePort.GetAccountAsync(AuthenticationWS.GetAccountRequest1 request)
        {
            return base.Channel.GetAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationWS.GetAccountResponse1> GetAccountAsync(AuthenticationWS.GetAccountRequest GetAccountRequest)
        {
            AuthenticationWS.GetAccountRequest1 inValue = new AuthenticationWS.GetAccountRequest1();
            inValue.GetAccountRequest = GetAccountRequest;
            return ((AuthenticationWS.AuthenticationServicePort)(this)).GetAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationWS.LogoutResponse1 AuthenticationWS.AuthenticationServicePort.Logout(AuthenticationWS.LogoutRequest1 request)
        {
            return base.Channel.Logout(request);
        }
        
        public AuthenticationWS.LogoutResponse Logout(AuthenticationWS.LogoutRequest LogoutRequest)
        {
            AuthenticationWS.LogoutRequest1 inValue = new AuthenticationWS.LogoutRequest1();
            inValue.LogoutRequest = LogoutRequest;
            AuthenticationWS.LogoutResponse1 retVal = ((AuthenticationWS.AuthenticationServicePort)(this)).Logout(inValue);
            return retVal.LogoutResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationWS.LogoutResponse1> AuthenticationWS.AuthenticationServicePort.LogoutAsync(AuthenticationWS.LogoutRequest1 request)
        {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationWS.LogoutResponse1> LogoutAsync(AuthenticationWS.LogoutRequest LogoutRequest)
        {
            AuthenticationWS.LogoutRequest1 inValue = new AuthenticationWS.LogoutRequest1();
            inValue.LogoutRequest = LogoutRequest;
            return ((AuthenticationWS.AuthenticationServicePort)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationWS.CheckUserResponse1 AuthenticationWS.AuthenticationServicePort.CheckUser(AuthenticationWS.CheckUserRequest1 request)
        {
            return base.Channel.CheckUser(request);
        }
        
        public AuthenticationWS.CheckUserResponse CheckUser(AuthenticationWS.CheckUserRequest CheckUserRequest)
        {
            AuthenticationWS.CheckUserRequest1 inValue = new AuthenticationWS.CheckUserRequest1();
            inValue.CheckUserRequest = CheckUserRequest;
            AuthenticationWS.CheckUserResponse1 retVal = ((AuthenticationWS.AuthenticationServicePort)(this)).CheckUser(inValue);
            return retVal.CheckUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationWS.CheckUserResponse1> AuthenticationWS.AuthenticationServicePort.CheckUserAsync(AuthenticationWS.CheckUserRequest1 request)
        {
            return base.Channel.CheckUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationWS.CheckUserResponse1> CheckUserAsync(AuthenticationWS.CheckUserRequest CheckUserRequest)
        {
            AuthenticationWS.CheckUserRequest1 inValue = new AuthenticationWS.CheckUserRequest1();
            inValue.CheckUserRequest = CheckUserRequest;
            return ((AuthenticationWS.AuthenticationServicePort)(this)).CheckUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthenticationWS.GetGibUserListResponse1 AuthenticationWS.AuthenticationServicePort.GetGibUserList(AuthenticationWS.GetGibUserListRequest1 request)
        {
            return base.Channel.GetGibUserList(request);
        }
        
        public AuthenticationWS.GetGibUserListResponse GetGibUserList(AuthenticationWS.GetGibUserListRequest GetGibUserListRequest)
        {
            AuthenticationWS.GetGibUserListRequest1 inValue = new AuthenticationWS.GetGibUserListRequest1();
            inValue.GetGibUserListRequest = GetGibUserListRequest;
            AuthenticationWS.GetGibUserListResponse1 retVal = ((AuthenticationWS.AuthenticationServicePort)(this)).GetGibUserList(inValue);
            return retVal.GetGibUserListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenticationWS.GetGibUserListResponse1> AuthenticationWS.AuthenticationServicePort.GetGibUserListAsync(AuthenticationWS.GetGibUserListRequest1 request)
        {
            return base.Channel.GetGibUserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationWS.GetGibUserListResponse1> GetGibUserListAsync(AuthenticationWS.GetGibUserListRequest GetGibUserListRequest)
        {
            AuthenticationWS.GetGibUserListRequest1 inValue = new AuthenticationWS.GetGibUserListRequest1();
            inValue.GetGibUserListRequest = GetGibUserListRequest;
            return ((AuthenticationWS.AuthenticationServicePort)(this)).GetGibUserListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationPort))
            {
                return new System.ServiceModel.EndpointAddress("https://efaturatest.izibiz.com.tr/AuthenticationWS");
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthenticationServicePortClient.GetBindingForEndpoint(EndpointConfiguration.AuthenticationPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthenticationServicePortClient.GetEndpointAddress(EndpointConfiguration.AuthenticationPort);
        }
        
        public enum EndpointConfiguration
        {
            
            AuthenticationPort,
        }
    }
}
