//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler hatalı davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingWS
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_ERRORType
    {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int eRROR_CODEField;
        
        private string eRROR_SHORT_DESField;
        
        private string eRROR_LONG_DESField;
        
        private string sTACKTRACEField;
        
        private int eRROR_ELEMENT_INDEXField;
        
        private bool eRROR_ELEMENT_INDEXFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long INTL_TXN_ID
        {
            get
            {
                return this.iNTL_TXN_IDField;
            }
            set
            {
                this.iNTL_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID
        {
            get
            {
                return this.cLIENT_TXN_IDField;
            }
            set
            {
                this.cLIENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int ERROR_CODE
        {
            get
            {
                return this.eRROR_CODEField;
            }
            set
            {
                this.eRROR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ERROR_SHORT_DES
        {
            get
            {
                return this.eRROR_SHORT_DESField;
            }
            set
            {
                this.eRROR_SHORT_DESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ERROR_LONG_DES
        {
            get
            {
                return this.eRROR_LONG_DESField;
            }
            set
            {
                this.eRROR_LONG_DESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string STACKTRACE
        {
            get
            {
                return this.sTACKTRACEField;
            }
            set
            {
                this.sTACKTRACEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int ERROR_ELEMENT_INDEX
        {
            get
            {
                return this.eRROR_ELEMENT_INDEXField;
            }
            set
            {
                this.eRROR_ELEMENT_INDEXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ERROR_ELEMENT_INDEXSpecified
        {
            get
            {
                return this.eRROR_ELEMENT_INDEXFieldSpecified;
            }
            set
            {
                this.eRROR_ELEMENT_INDEXFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_RETURNType
    {
        
        private long iNTL_TXN_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private int rETURN_CODEField;
        
        private string[] wARNINGSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long INTL_TXN_ID
        {
            get
            {
                return this.iNTL_TXN_IDField;
            }
            set
            {
                this.iNTL_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID
        {
            get
            {
                return this.cLIENT_TXN_IDField;
            }
            set
            {
                this.cLIENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int RETURN_CODE
        {
            get
            {
                return this.rETURN_CODEField;
            }
            set
            {
                this.rETURN_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WARNINGS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string[] WARNINGS
        {
            get
            {
                return this.wARNINGSField;
            }
            set
            {
                this.wARNINGSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class PRODUCT
    {
        
        private string eFATURAField;
        
        private string eARSIVField;
        
        private string eIRSALIYEField;
        
        private string eSMMField;
        
        private string eMMField;
        
        private string eMUTABAKATField;
        
        private string sMSField;
        
        private string mAILField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string EFATURA
        {
            get
            {
                return this.eFATURAField;
            }
            set
            {
                this.eFATURAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string EARSIV
        {
            get
            {
                return this.eARSIVField;
            }
            set
            {
                this.eARSIVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string EIRSALIYE
        {
            get
            {
                return this.eIRSALIYEField;
            }
            set
            {
                this.eIRSALIYEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string ESMM
        {
            get
            {
                return this.eSMMField;
            }
            set
            {
                this.eSMMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=4)]
        public string EMM
        {
            get
            {
                return this.eMMField;
            }
            set
            {
                this.eMMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=5)]
        public string EMUTABAKAT
        {
            get
            {
                return this.eMUTABAKATField;
            }
            set
            {
                this.eMUTABAKATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=6)]
        public string SMS
        {
            get
            {
                return this.sMSField;
            }
            set
            {
                this.sMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=7)]
        public string MAIL
        {
            get
            {
                return this.mAILField;
            }
            set
            {
                this.mAILField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class USAGE
    {
        
        private string pERIODField;
        
        private string tOTAL_USAGEField;
        
        private PRODUCT pRODUCTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string PERIOD
        {
            get
            {
                return this.pERIODField;
            }
            set
            {
                this.pERIODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string TOTAL_USAGE
        {
            get
            {
                return this.tOTAL_USAGEField;
            }
            set
            {
                this.tOTAL_USAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PRODUCT PRODUCT
        {
            get
            {
                return this.pRODUCTField;
            }
            set
            {
                this.pRODUCTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUsageResponse
    {
        
        private USAGE[] lAST_PROCESS_TIMEField;
        
        private REQUEST_RETURNType rEQUEST_RETURNField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public USAGE[] LAST_PROCESS_TIME
        {
            get
            {
                return this.lAST_PROCESS_TIMEField;
            }
            set
            {
                this.lAST_PROCESS_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public REQUEST_RETURNType REQUEST_RETURN
        {
            get
            {
                return this.rEQUEST_RETURNField;
            }
            set
            {
                this.rEQUEST_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public REQUEST_ERRORType ERROR_TYPE
        {
            get
            {
                return this.eRROR_TYPEField;
            }
            set
            {
                this.eRROR_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class ATTRIBUTESTYPE
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private string nAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NAME
        {
            get
            {
                return this.nAMEField;
            }
            set
            {
                this.nAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public partial class CHANGE_INFOType
    {
        
        private System.DateTime cDATEField;
        
        private long cPOSITION_IDField;
        
        private long cUSER_IDField;
        
        private System.DateTime uDATEField;
        
        private bool uDATEFieldSpecified;
        
        private long uPOSITION_IDField;
        
        private bool uPOSITION_IDFieldSpecified;
        
        private long uUSER_IDField;
        
        private bool uUSER_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime CDATE
        {
            get
            {
                return this.cDATEField;
            }
            set
            {
                this.cDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long CPOSITION_ID
        {
            get
            {
                return this.cPOSITION_IDField;
            }
            set
            {
                this.cPOSITION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long CUSER_ID
        {
            get
            {
                return this.cUSER_IDField;
            }
            set
            {
                this.cUSER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime UDATE
        {
            get
            {
                return this.uDATEField;
            }
            set
            {
                this.uDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UDATESpecified
        {
            get
            {
                return this.uDATEFieldSpecified;
            }
            set
            {
                this.uDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long UPOSITION_ID
        {
            get
            {
                return this.uPOSITION_IDField;
            }
            set
            {
                this.uPOSITION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UPOSITION_IDSpecified
        {
            get
            {
                return this.uPOSITION_IDFieldSpecified;
            }
            set
            {
                this.uPOSITION_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long UUSER_ID
        {
            get
            {
                return this.uUSER_IDField;
            }
            set
            {
                this.uUSER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UUSER_IDSpecified
        {
            get
            {
                return this.uUSER_IDFieldSpecified;
            }
            set
            {
                this.uUSER_IDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST_HEADERType
    {
        
        private string sESSION_IDField;
        
        private string cLIENT_TXN_IDField;
        
        private long iNTL_TXN_IDField;
        
        private bool iNTL_TXN_IDFieldSpecified;
        
        private long iNTL_PARENT_TXN_IDField;
        
        private bool iNTL_PARENT_TXN_IDFieldSpecified;
        
        private System.DateTime aCTION_DATEField;
        
        private bool aCTION_DATEFieldSpecified;
        
        private CHANGE_INFOType cHANGE_INFOField;
        
        private string rEASONField;
        
        private string aPPLICATION_NAMEField;
        
        private string hOSTNAMEField;
        
        private string cHANNEL_NAMEField;
        
        private string sIMULATION_FLAGField;
        
        private string cOMPRESSEDField;
        
        private ATTRIBUTESTYPE[] aTTRIBUTESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string SESSION_ID
        {
            get
            {
                return this.sESSION_IDField;
            }
            set
            {
                this.sESSION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string CLIENT_TXN_ID
        {
            get
            {
                return this.cLIENT_TXN_IDField;
            }
            set
            {
                this.cLIENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long INTL_TXN_ID
        {
            get
            {
                return this.iNTL_TXN_IDField;
            }
            set
            {
                this.iNTL_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_TXN_IDSpecified
        {
            get
            {
                return this.iNTL_TXN_IDFieldSpecified;
            }
            set
            {
                this.iNTL_TXN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long INTL_PARENT_TXN_ID
        {
            get
            {
                return this.iNTL_PARENT_TXN_IDField;
            }
            set
            {
                this.iNTL_PARENT_TXN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INTL_PARENT_TXN_IDSpecified
        {
            get
            {
                return this.iNTL_PARENT_TXN_IDFieldSpecified;
            }
            set
            {
                this.iNTL_PARENT_TXN_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime ACTION_DATE
        {
            get
            {
                return this.aCTION_DATEField;
            }
            set
            {
                this.aCTION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ACTION_DATESpecified
        {
            get
            {
                return this.aCTION_DATEFieldSpecified;
            }
            set
            {
                this.aCTION_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public CHANGE_INFOType CHANGE_INFO
        {
            get
            {
                return this.cHANGE_INFOField;
            }
            set
            {
                this.cHANGE_INFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=6)]
        public string REASON
        {
            get
            {
                return this.rEASONField;
            }
            set
            {
                this.rEASONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=7)]
        public string APPLICATION_NAME
        {
            get
            {
                return this.aPPLICATION_NAMEField;
            }
            set
            {
                this.aPPLICATION_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=8)]
        public string HOSTNAME
        {
            get
            {
                return this.hOSTNAMEField;
            }
            set
            {
                this.hOSTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=9)]
        public string CHANNEL_NAME
        {
            get
            {
                return this.cHANNEL_NAMEField;
            }
            set
            {
                this.cHANNEL_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=10)]
        public string SIMULATION_FLAG
        {
            get
            {
                return this.sIMULATION_FLAGField;
            }
            set
            {
                this.sIMULATION_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=11)]
        public string COMPRESSED
        {
            get
            {
                return this.cOMPRESSEDField;
            }
            set
            {
                this.cOMPRESSEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ATTRIBUTES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public ATTRIBUTESTYPE[] ATTRIBUTES
        {
            get
            {
                return this.aTTRIBUTESField;
            }
            set
            {
                this.aTTRIBUTESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetBalanceRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUsageRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetCreditRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/entity")]
    public partial class REQUEST
    {
        
        private REQUEST_HEADERType rEQUEST_HEADERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public REQUEST_HEADERType REQUEST_HEADER
        {
            get
            {
                return this.rEQUEST_HEADERField;
            }
            set
            {
                this.rEQUEST_HEADERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetBalanceRequest : REQUEST
    {
        
        private FLAG_VALUE bALANCE_DETAIL_FLAGField;
        
        public GetBalanceRequest()
        {
            this.bALANCE_DETAIL_FLAGField = FLAG_VALUE.N;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FLAG_VALUE BALANCE_DETAIL_FLAG
        {
            get
            {
                return this.bALANCE_DETAIL_FLAGField;
            }
            set
            {
                this.bALANCE_DETAIL_FLAGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/common")]
    public enum FLAG_VALUE
    {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetUsageRequest : REQUEST
    {
        
        private string pERIODField;
        
        private PRODUCT_TYPE pRODUCT_TYPEField;
        
        private DIRECTION dIRECTIONField;
        
        public GetUsageRequest()
        {
            this.pRODUCT_TYPEField = PRODUCT_TYPE.ALL;
            this.dIRECTIONField = DIRECTION.ALL;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string PERIOD
        {
            get
            {
                return this.pERIODField;
            }
            set
            {
                this.pERIODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PRODUCT_TYPE PRODUCT_TYPE
        {
            get
            {
                return this.pRODUCT_TYPEField;
            }
            set
            {
                this.pRODUCT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DIRECTION DIRECTION
        {
            get
            {
                return this.dIRECTIONField;
            }
            set
            {
                this.dIRECTIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum PRODUCT_TYPE
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        EFATURA,
        
        /// <remarks/>
        EARSIV,
        
        /// <remarks/>
        EIRSALIYE,
        
        /// <remarks/>
        ESMM,
        
        /// <remarks/>
        EMM,
        
        /// <remarks/>
        EMUTABAKAT,
        
        /// <remarks/>
        SMS,
        
        /// <remarks/>
        MAIL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public enum DIRECTION
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        OUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetCreditRequest : REQUEST
    {
        
        private FLAG_VALUE cREDIT_DETAIL_FLAGField;
        
        public GetCreditRequest()
        {
            this.cREDIT_DETAIL_FLAGField = FLAG_VALUE.N;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FLAG_VALUE CREDIT_DETAIL_FLAG
        {
            get
            {
                return this.cREDIT_DETAIL_FLAGField;
            }
            set
            {
                this.cREDIT_DETAIL_FLAGField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", ConfigurationName="BillingWS.BillingServicePort")]
    public interface BillingServicePort
    {
        
        // CODEGEN: GetUsage işlemi RPC ya da belge sarmalamalı olmadığından, ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetUsageRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetUsageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BillingWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetUsage/Fault/RequestFaultMess" +
            "age", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        BillingWS.GetUsageResponse1 GetUsage(BillingWS.GetUsageRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetUsageRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetUsageResponse")]
        System.Threading.Tasks.Task<BillingWS.GetUsageResponse1> GetUsageAsync(BillingWS.GetUsageRequest1 request);
        
        // CODEGEN: GetBalance işlemi RPC ya da belge sarmalamalı olmadığından, ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetBalanceRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetBalanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BillingWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetBalance/Fault/RequestFaultMe" +
            "ssage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        BillingWS.GetBalanceResponse1 GetBalance(BillingWS.GetBalanceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetBalanceRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetBalanceResponse")]
        System.Threading.Tasks.Task<BillingWS.GetBalanceResponse1> GetBalanceAsync(BillingWS.GetBalanceRequest1 request);
        
        // CODEGEN: GetCredit işlemi RPC ya da belge sarmalamalı olmadığından, ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetCreditRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetCreditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BillingWS.REQUEST_ERRORType), Action="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetCredit/Fault/RequestFaultMes" +
            "sage", Name="RequestFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(REQUEST))]
        BillingWS.GetCreditResponse1 GetCredit(BillingWS.GetCreditRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetCreditRequest", ReplyAction="http://schemas.i2i.com/ei/wsdl/BillingServicePort/GetCreditResponse")]
        System.Threading.Tasks.Task<BillingWS.GetCreditResponse1> GetCreditAsync(BillingWS.GetCreditRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsageRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public BillingWS.GetUsageRequest GetUsageRequest;
        
        public GetUsageRequest1()
        {
        }
        
        public GetUsageRequest1(BillingWS.GetUsageRequest GetUsageRequest)
        {
            this.GetUsageRequest = GetUsageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsageResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public BillingWS.GetUsageResponse GetUsageResponse;
        
        public GetUsageResponse1()
        {
        }
        
        public GetUsageResponse1(BillingWS.GetUsageResponse GetUsageResponse)
        {
            this.GetUsageResponse = GetUsageResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetBalanceResponse
    {
        
        private string tOTAL_BALANCEField;
        
        private string iNVOICE_COUNTField;
        
        private string mESSAGEField;
        
        private INVOICE[] bALANCE_DETAILField;
        
        private REQUEST_RETURNType rEQUEST_RETURNField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string TOTAL_BALANCE
        {
            get
            {
                return this.tOTAL_BALANCEField;
            }
            set
            {
                this.tOTAL_BALANCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string INVOICE_COUNT
        {
            get
            {
                return this.iNVOICE_COUNTField;
            }
            set
            {
                this.iNVOICE_COUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public INVOICE[] BALANCE_DETAIL
        {
            get
            {
                return this.bALANCE_DETAILField;
            }
            set
            {
                this.bALANCE_DETAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public REQUEST_RETURNType REQUEST_RETURN
        {
            get
            {
                return this.rEQUEST_RETURNField;
            }
            set
            {
                this.rEQUEST_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public REQUEST_ERRORType ERROR_TYPE
        {
            get
            {
                return this.eRROR_TYPEField;
            }
            set
            {
                this.eRROR_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class INVOICE
    {
        
        private string iNVOICE_NOField;
        
        private string iNVOICE_DATEField;
        
        private string pERIODField;
        
        private string pAYABLE_AMOUNTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string INVOICE_NO
        {
            get
            {
                return this.iNVOICE_NOField;
            }
            set
            {
                this.iNVOICE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string INVOICE_DATE
        {
            get
            {
                return this.iNVOICE_DATEField;
            }
            set
            {
                this.iNVOICE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string PERIOD
        {
            get
            {
                return this.pERIODField;
            }
            set
            {
                this.pERIODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string PAYABLE_AMOUNT
        {
            get
            {
                return this.pAYABLE_AMOUNTField;
            }
            set
            {
                this.pAYABLE_AMOUNTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public BillingWS.GetBalanceRequest GetBalanceRequest;
        
        public GetBalanceRequest1()
        {
        }
        
        public GetBalanceRequest1(BillingWS.GetBalanceRequest GetBalanceRequest)
        {
            this.GetBalanceRequest = GetBalanceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public BillingWS.GetBalanceResponse GetBalanceResponse;
        
        public GetBalanceResponse1()
        {
        }
        
        public GetBalanceResponse1(BillingWS.GetBalanceResponse GetBalanceResponse)
        {
            this.GetBalanceResponse = GetBalanceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class GetCreditResponse
    {
        
        private string cREDIT_LOADEDField;
        
        private string cREDIT_BALANCEField;
        
        private string lAST_PROCESS_TIMEField;
        
        private string mESSAGEField;
        
        private CREDIT[] cREDIT_DETAILField;
        
        private REQUEST_RETURNType rEQUEST_RETURNField;
        
        private REQUEST_ERRORType eRROR_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string CREDIT_LOADED
        {
            get
            {
                return this.cREDIT_LOADEDField;
            }
            set
            {
                this.cREDIT_LOADEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string CREDIT_BALANCE
        {
            get
            {
                return this.cREDIT_BALANCEField;
            }
            set
            {
                this.cREDIT_BALANCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string LAST_PROCESS_TIME
        {
            get
            {
                return this.lAST_PROCESS_TIMEField;
            }
            set
            {
                this.lAST_PROCESS_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CREDIT[] CREDIT_DETAIL
        {
            get
            {
                return this.cREDIT_DETAILField;
            }
            set
            {
                this.cREDIT_DETAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public REQUEST_RETURNType REQUEST_RETURN
        {
            get
            {
                return this.rEQUEST_RETURNField;
            }
            set
            {
                this.rEQUEST_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public REQUEST_ERRORType ERROR_TYPE
        {
            get
            {
                return this.eRROR_TYPEField;
            }
            set
            {
                this.eRROR_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.i2i.com/ei/wsdl")]
    public partial class CREDIT
    {
        
        private string cDATEField;
        
        private string eXPIRE_DATEField;
        
        private string lOADED_AMOUNTField;
        
        private string rEMAINING_AMOUNTField;
        
        private string tARIFF_NAMEField;
        
        private string pRICEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
        public string CDATE
        {
            get
            {
                return this.cDATEField;
            }
            set
            {
                this.cDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
        public string EXPIRE_DATE
        {
            get
            {
                return this.eXPIRE_DATEField;
            }
            set
            {
                this.eXPIRE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
        public string LOADED_AMOUNT
        {
            get
            {
                return this.lOADED_AMOUNTField;
            }
            set
            {
                this.lOADED_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
        public string REMAINING_AMOUNT
        {
            get
            {
                return this.rEMAINING_AMOUNTField;
            }
            set
            {
                this.rEMAINING_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=4)]
        public string TARIFF_NAME
        {
            get
            {
                return this.tARIFF_NAMEField;
            }
            set
            {
                this.tARIFF_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=5)]
        public string PRICE
        {
            get
            {
                return this.pRICEField;
            }
            set
            {
                this.pRICEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public BillingWS.GetCreditRequest GetCreditRequest;
        
        public GetCreditRequest1()
        {
        }
        
        public GetCreditRequest1(BillingWS.GetCreditRequest GetCreditRequest)
        {
            this.GetCreditRequest = GetCreditRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.i2i.com/ei/wsdl", Order=0)]
        public BillingWS.GetCreditResponse GetCreditResponse;
        
        public GetCreditResponse1()
        {
        }
        
        public GetCreditResponse1(BillingWS.GetCreditResponse GetCreditResponse)
        {
            this.GetCreditResponse = GetCreditResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface BillingServicePortChannel : BillingWS.BillingServicePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class BillingServicePortClient : System.ServiceModel.ClientBase<BillingWS.BillingServicePort>, BillingWS.BillingServicePort
    {
        
        /// <summary>
        /// Hizmet uç noktasını yapılandırmak için bu kısmi metodu uygulayın.
        /// </summary>
        /// <param name="serviceEndpoint">Yapılandırılacak uç nokta</param>
        /// <param name="clientCredentials">İstemci kimlik bilgileri</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BillingServicePortClient() : 
                base(BillingServicePortClient.GetDefaultBinding(), BillingServicePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BillingPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BillingServicePortClient(EndpointConfiguration endpointConfiguration) : 
                base(BillingServicePortClient.GetBindingForEndpoint(endpointConfiguration), BillingServicePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BillingServicePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BillingServicePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BillingServicePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BillingServicePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BillingServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillingWS.GetUsageResponse1 BillingWS.BillingServicePort.GetUsage(BillingWS.GetUsageRequest1 request)
        {
            return base.Channel.GetUsage(request);
        }
        
        public BillingWS.GetUsageResponse GetUsage(BillingWS.GetUsageRequest GetUsageRequest)
        {
            BillingWS.GetUsageRequest1 inValue = new BillingWS.GetUsageRequest1();
            inValue.GetUsageRequest = GetUsageRequest;
            BillingWS.GetUsageResponse1 retVal = ((BillingWS.BillingServicePort)(this)).GetUsage(inValue);
            return retVal.GetUsageResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillingWS.GetUsageResponse1> BillingWS.BillingServicePort.GetUsageAsync(BillingWS.GetUsageRequest1 request)
        {
            return base.Channel.GetUsageAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillingWS.GetUsageResponse1> GetUsageAsync(BillingWS.GetUsageRequest GetUsageRequest)
        {
            BillingWS.GetUsageRequest1 inValue = new BillingWS.GetUsageRequest1();
            inValue.GetUsageRequest = GetUsageRequest;
            return ((BillingWS.BillingServicePort)(this)).GetUsageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillingWS.GetBalanceResponse1 BillingWS.BillingServicePort.GetBalance(BillingWS.GetBalanceRequest1 request)
        {
            return base.Channel.GetBalance(request);
        }
        
        public BillingWS.GetBalanceResponse GetBalance(BillingWS.GetBalanceRequest GetBalanceRequest)
        {
            BillingWS.GetBalanceRequest1 inValue = new BillingWS.GetBalanceRequest1();
            inValue.GetBalanceRequest = GetBalanceRequest;
            BillingWS.GetBalanceResponse1 retVal = ((BillingWS.BillingServicePort)(this)).GetBalance(inValue);
            return retVal.GetBalanceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillingWS.GetBalanceResponse1> BillingWS.BillingServicePort.GetBalanceAsync(BillingWS.GetBalanceRequest1 request)
        {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillingWS.GetBalanceResponse1> GetBalanceAsync(BillingWS.GetBalanceRequest GetBalanceRequest)
        {
            BillingWS.GetBalanceRequest1 inValue = new BillingWS.GetBalanceRequest1();
            inValue.GetBalanceRequest = GetBalanceRequest;
            return ((BillingWS.BillingServicePort)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillingWS.GetCreditResponse1 BillingWS.BillingServicePort.GetCredit(BillingWS.GetCreditRequest1 request)
        {
            return base.Channel.GetCredit(request);
        }
        
        public BillingWS.GetCreditResponse GetCredit(BillingWS.GetCreditRequest GetCreditRequest)
        {
            BillingWS.GetCreditRequest1 inValue = new BillingWS.GetCreditRequest1();
            inValue.GetCreditRequest = GetCreditRequest;
            BillingWS.GetCreditResponse1 retVal = ((BillingWS.BillingServicePort)(this)).GetCredit(inValue);
            return retVal.GetCreditResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillingWS.GetCreditResponse1> BillingWS.BillingServicePort.GetCreditAsync(BillingWS.GetCreditRequest1 request)
        {
            return base.Channel.GetCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillingWS.GetCreditResponse1> GetCreditAsync(BillingWS.GetCreditRequest GetCreditRequest)
        {
            BillingWS.GetCreditRequest1 inValue = new BillingWS.GetCreditRequest1();
            inValue.GetCreditRequest = GetCreditRequest;
            return ((BillingWS.BillingServicePort)(this)).GetCreditAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BillingPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BillingPort))
            {
                return new System.ServiceModel.EndpointAddress("https://efaturatest.izibiz.com.tr/BillingWS");
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BillingServicePortClient.GetBindingForEndpoint(EndpointConfiguration.BillingPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BillingServicePortClient.GetEndpointAddress(EndpointConfiguration.BillingPort);
        }
        
        public enum EndpointConfiguration
        {
            
            BillingPort,
        }
    }
}
